gcp_project: "your-gcp-project-id"
bq_dataset: "my_sample_dataset"
bq_table: "my_sample_table"
bq_location: "US"
bq_table_schema:
  - name: "id"
    type: "STRING"
    mode: "REQUIRED"
  - name: "name"
    type: "STRING"
    mode: "NULLABLE"
  - name: "age"
    type: "INTEGER"
    mode: "NULLABLE"
  - name: "created_at"
    type: "TIMESTAMP"
    mode: "NULLABLE"
