---
  - name: "GCP and BigQuery Operations Playbook"
    hosts: localhost
    gather_facts: no
    tasks:
  
      - name: "List GCP resources (VMs, Service Accounts, etc.)"
        include_role:
          name: gcp_list_resources
        tags: 
          - gcp_list_resources
  
      - name: "BigQuery Operations (Dataset/Table Creation)"
        include_role:
          name: bq_operations
        tags: 
          - bq_operations
  
