---
  - name: "List all VMs in the project across all zones"
    gcp_compute_instance_info:
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      service_account_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
    register: vm_info
  
  - name: "Show the virtual machines"
    debug:
      var: vm_info
  