---
  - name: "List all VMs in the project across specified zones"
    gcp_compute_instance_info:
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      service_account_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
      zone: "{{ item }}"
    loop: "{{ gcp_zones }}"
    register: vm_info_per_zone
  
  - name: "Show the virtual machines from all zones"
    debug:
      var: vm_info_per_zone
  